[package]
name = "mitfahrzentrale"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
serde = "1.0.228"
sqlx = { version = "0.8.6", features = [ "runtime-tokio", "postgres", "derive" ] }
tokio = { version = "1.49.0", features = ["full"] }
